export enum PixelActions {
    SET_PIXEL_TABLE = 'SET_PIXEL',
    SET_PIXE_SIZE = 'SET_PIXE_SIZE',
    SET_PIXEL_HEIGHT = 'SET_PIXEL_HEIGHT',
    SET_PIXEL_WIDTH = 'SET_PIXEL_HEIGHT'
}

export enum ColorActions {
    SET_FIRST_COLOR = 'SET_FIRST_COLOR',
    SET_SECOND_COLOR = 'SET_SECOND_COLOR'
}

